# Generated by Django 5.2.1 on 2025-06-19 10:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('default_category', models.CharField(choices=[('', 'select category'), ('factory', 'Factory Customer'), ('distributor', 'Distributor Customer'), ('wholesale', 'Wholesale Customer'), ('Towns', 'Towns Customer'), ('Retail customer', 'Retail customer')], default='wholesale', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_category', models.CharField(choices=[('factory', 'Factory Customer'), ('distributor', 'Distributor Customer'), ('wholesale', 'Wholesale Customer'), ('Retail customer', 'Retail customer'), ('Towns', 'Towns Customer')], default='is_walk_in', max_length=20)),
                ('vat_variation', models.CharField(choices=[('with_vat', 'With VAT'), ('without_vat', 'Without VAT')], default='with_vat', max_length=20)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('paid_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('store', models.CharField(choices=[('mcdave', 'McDave Store'), ('kisii', 'Kisii Store'), ('offshore', 'Offshore Store')], default='mcdave', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.customer')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/products/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('limited', 'Limited Deal'), ('offer', 'In Offer')], default='available', max_length=20)),
                ('factory_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Base price before markups', max_digits=10)),
                ('distributor_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Base price before markups', max_digits=10)),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Base price before markups', max_digits=10)),
                ('offshore_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Base price before markups', max_digits=10)),
                ('barcode', models.CharField(blank=True, help_text='Unique barcode for the product', max_length=100, null=True, unique=True)),
                ('retail_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Retail price for all customers', max_digits=10)),
                ('mcdave_stock', models.PositiveIntegerField(default=0, help_text='Stock at McDave Store')),
                ('kisii_stock', models.PositiveIntegerField(default=0, help_text='Stock at Kisii Store')),
                ('offshore_stock', models.PositiveIntegerField(default=0, help_text='Stock at Offshore Store')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('variance', models.DecimalField(decimal_places=2, default=0, help_text='Additional amount added to unit price', max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, choices=[('Sales', 'Sales'), ('Executive', 'Executive')], max_length=50, null=True)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_change_department', 'Can change department field')],
            },
        ),
    ]
