# Generated by Django 5.2.1 on 2025-07-15 09:10

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customer_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='formatted_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,14}$', 'Phone number must be 10-14 digits, starting with 0 or +')]),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='store_categ_name_1278fd_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['sales_person'], name='store_custo_sales_p_f425b6_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_at'], name='store_custo_created_b1048d_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['customer'], name='store_deal_custome_766fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['created_at'], name='store_deal_created_b02745_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer'], name='store_order_custome_5796e7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['sales_person'], name='store_order_sales_p_dc8be9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date'], name='store_order_order_d_1d849c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['paid_status'], name='store_order_paid_st_36a903_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store'], name='store_order_store_77c1c5_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='store_order_order_i_70b6d9_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='store_order_product_056298_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='store_produ_categor_6683b7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='store_produ_barcode_f818f0_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='store_userp_user_id_0a973c_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['department'], name='store_userp_departm_2511cc_idx'),
        ),
    ]
