# Generated by Django 5.2.1 on 2025-07-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customer_formatted_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='store_categ_name_1278fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='store_custo_sales_p_f425b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='store_custo_created_b1048d_idx',
        ),
        migrations.RemoveIndex(
            model_name='deal',
            name='store_deal_custome_766fa7_idx',
        ),
        migrations.RemoveIndex(
            model_name='deal',
            name='store_deal_created_b02745_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='store_order_custome_5796e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='store_order_sales_p_dc8be9_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='store_order_order_d_1d849c_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='store_order_paid_st_36a903_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='store_order_store_77c1c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='store_order_order_i_70b6d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='store_order_product_056298_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='store_produ_categor_6683b7_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='store_produ_barcode_f818f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='store_userp_user_id_0a973c_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='store_userp_departm_2511cc_idx',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='formatted_phone_number',
        ),
    ]
