# Generated by Django 5.2.1 on 2025-08-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_order_customer_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_category',
            field=models.CharField(choices=[('factory', 'Factory Customer'), ('distributor', 'Distributor Customer'), ('wholesale', 'Wholesale Customer'), ('Retail customer', 'Retail customer'), ('Towns', 'Towns Customer')], default='wholesale', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('partially_paid', 'Partially Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='store',
            field=models.CharField(choices=[('mcdave', 'McDave Store'), ('kisii', 'Kisii Store'), ('offshore', 'Offshore Store')], default='mcdave', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='vat_variation',
            field=models.CharField(choices=[('with_vat', 'With VAT'), ('without_vat', 'Without VAT')], default='with_vat', max_length=20),
        ),
    ]
