# Generated by Django 5.2.1 on 2025-10-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_order_customer_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='store',
            field=models.CharField(choices=[('mcdave', 'McDave Store'), ('kisii', 'Mombasa Store'), ('offshore', 'Offshore Store')], default='mcdave', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='kisii_stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock at offshore store MBS'),
        ),
        migrations.AlterField(
            model_name='product',
            name='offshore_stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock at Offshore Store NRB'),
        ),
    ]
