# Generated by Django 5.2.1 on 2025-11-03 09:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_order_store_alter_product_kisii_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='variance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional amount added to unit price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-50.00')), django.core.validators.MaxValueValidator(Decimal('50.00'))]),
        ),
    ]
