# Generated by Django 5.2.1 on 2025-11-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_deal_original_quantity_order_amount_paid_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='original_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
