# Generated by Django 5.2.1 on 2026-01-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_orderitem_original_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Delivery fee to be added to the order total', max_digits=10),
        ),
    ]
