# Generated by Django 5.2.1 on 2025-09-04 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordreset',
            options={'ordering': ['-created_when']},
        ),
        migrations.AlterModelTable(
            name='passwordreset',
            table='password_reset',
        ),
    ]
